name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: ${{ matrix.ros_distro }} (node ${{ matrix.node_version }})
    if: ${{ github.actor != 'RWT-bot' }}
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.ros_distro }}-ros-core
      options: --cap-add=SYS_ADMIN
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [noetic]
        node_version: [18, 20]
    env:
      ROS_DISTRO: ${{ matrix.ros_distro }}
    steps:
      - name: Install git in container
        run: |
          apt-get update
          apt-get install -q -y git
      - name: Set git safe directory
        run: |
          git config --global safe.directory '*'
      - uses: actions/checkout@v4
        env:
          TOKEN: "${{ github.event_name == 'push' && endsWith(github.ref, 'develop') && matrix.ros_distro == 'noetic' && secrets.RWT_BOT_PAT || github.token }}"
        with:
          token: ${{ env.TOKEN }}
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node_version }}
      - name: Own /github/home and PWD
        run: |
          chown -hR 1001:121 /github/home .
      - name: Install apt dependencies
        run: |
          apt-get install -q -y libasound2 libnss3 ros-$ROS_DISTRO-rosbridge-server ros-$ROS_DISTRO-tf2-web-republisher ros-$ROS_DISTRO-common-tutorials ros-$ROS_DISTRO-rospy-tutorials ros-$ROS_DISTRO-actionlib-tutorials
      - name: Tests
        run: |
          bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && bash test/build.bash"

  ci_ros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - noetic
          - humble
          - iron
          - jazzy
          - rolling
        include:
          # Noetic Ninjemys (May 2020 - May 2025)
          - docker_image: ubuntu:focal
            ros_distribution: noetic
            ros_version: 1

          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2

          # Iron Irwini (May 2023 - November 2024)
          - docker_image: ubuntu:jammy
            ros_distribution: iron
            ros_version: 2

          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: ubuntu:noble
            ros_distribution: jazzy
            ros_version: 2

          # Rolling Ridley (No End-Of-Life)
          - docker_image: ubuntu:noble
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install --no-install-recommends -y \
          ros-${{ matrix.ros_distribution }}-rosbridge-server
